### ISSUE TITLE
How can this work with tailwindcss and postcss-purgecss?

### ISSUE THREAD

**Issue by brielov** [google/postcss-rename#24]

**Comment by J05HI** [comment]
@brielov @iflan @nanaze @rzhw 
I tried the same. It only replaces the class names in CSS. In HTML they don't get replaced.
Is there an example?

**Comment by rzhw** [comment]
This plugin doesn't rewrite class names in JS or HTML; you'll need something that can consume the map passed to `outputMapCallback` by this plugin. That could be a Webpack plugin, for example.

There isn't one we know of currently, but we're happy to add links in the README.
